### ISSUE TITLE
[category] boxconstraints maxheight is incorrect, when heightPerMin is greater than 1

### ISSUE THREAD

**Issue by baraya** [samderlust/calendar_day_view#25]
In ```category_overflow_calendar_day_view.dart _DayViewBody class``` the event box constraint maxHeight is the event duration in minutes. But if I increase the heightPerMin for the calendar, then the event height is smaller than the actual duration height. Workaround was to pass a constraint with the maxHeight being the durationInMins * heightPerMin (from the calendar constructor).

Workaround
```
  static const double heightPerMin = 5;
...
eventBuilder: (constraints, category, time, event) {
return Container(
  constraints: BoxConstraints(
                              minWidth: 50
                              maxHeight: event.durationInMins * heightPerMin,
  )
)})
```

**Comment by samderlust** [comment]
Thanks @baraya 
Fixed in V4.0.1
