### ISSUE TITLE
Incorrect time is shown for 12:00 PM when using 12 hour time format

### ISSUE THREAD

**Issue by ArizArmeidi** [samderlust/calendar_day_view#27]
![image](https://github.com/user-attachments/assets/79ae2ef3-ed5f-41e0-aeba-3efbbc0cd755)
When using the 12 hour time format the time text is showing **00:00 PM** which is incorrect instead it should show **12:00 PM**
![image](https://github.com/user-attachments/assets/ab66c995-1601-4067-94ad-43b2d3d1aec3)

after looking at the code I noticed the problem was caused by the date time extension specifically on the hourDisplay12 getter that is written like this
```dart
 String get hourDisplay12 =>
      "${(hour % 12).toString().padLeft(2, '0')}:${minute.toString().padLeft(2, '0')} ${hour >= 12 ? 'PM' : 'AM'}";
```
Which is causing the 12 to be 0, I suggest you can modify the code to this so that it will display the time as expected
```dart
 String get hourDisplay12 {
    if (hour == 12) {
      return "${(hour).toString().padLeft(2, '0')}:${minute.toString().padLeft(2, '0')} ${hour >= 12 ? 'PM' : 'AM'}";
    }
    return "${(hour % 12).toString().padLeft(2, '0')}:${minute.toString().padLeft(2, '0')} ${hour >= 12 ? 'PM' : 'AM'}";
  }
```
![image](https://github.com/user-attachments/assets/55e50585-b8b8-4c56-95d6-d61d955c7d31)

**Comment by samderlust** [comment]
Hi @ArizArmeidi, 
Thanks so much for finding the issue. I'll release a patch soon

**Comment by ArizArmeidi** [comment]
Thanks for the quick response 😁
