### ISSUE TITLE
Customize time label format

### ISSUE THREAD

**Issue by ninasarabia** [samderlust/calendar_day_view#32]
I'm using the `CalendarDayView.overflow`. Unless I'm missing it in the documentation, I can't find a way to customize the format of the time labels on the left. Rather than showing 06:00 PM, I'd like to show 6PM, or potentially show other artifacts in that column.

(Also thanks for this package!)

**Comment by samderlust** [comment]
@ninasarabia I have thought about allowing users to customize this time label before but didn't have a chance to make it. 
I'll add it soon and let you know

**Comment by samderlust** [comment]
@ninasarabia Published in v4.0.2

**Comment by ninasarabia** [comment]
Wow — thanks for the wild turnaround! 🙌🏽
