### ISSUE TITLE
OverFlowCalendarDayView events list is not invariant

### ISSUE THREAD

**Issue by Paul-Todd** [samderlust/calendar_day_view#5]
I noticed that the list that is passed in is modified by the control which may impact the caller if they have the list sorted in their own order.

The list.sort function does an inplace sort so you probably intended this to be outside the function call but also it now assumes the widget.events is a modifiable list which is unfortunately owned by the caller.

Specifically line line 110
```
    _overflowEvents = processOverflowEvents(widget.events
      ..sort(
        (a, b) => a.compare(b),

```

sort modifies the list

Noticed this as I was passing in a list wrapped around List.unmodifiable from a riverpod provider.

Can raise a PR for this as well if neccessary - shallow copy the list when creating the control would be the fix.

**Comment by samderlust** [comment]
@Paul-Todd   sorry for late response. some how I missed this. I just did a test a notice the same issue. although you can provide a shallow copy to the DayView but I think it would be better if we handle it inside the package too.
Please raise an PR  as you want

**Comment by samderlust** [comment]
@Paul-Todd  I will publish version 2.0 with some updates and add one more dayview. So I will fix this issue in that version too.

**Comment by Paul-Todd** [comment]
Thanks!
